node {



stage('Check-out') {
echo 'From check-out stage'
git branch: 'main', url: 'https://github.com/khadar0463/sample'
}



stage('Bazel Build') {
echo 'From Bazel Build stage'
	sh '''
	pwd 
	ls
	cd cpp-tutorial/stage3
	bazel build //main:hello-world
	bazel-bin/main/hello-world
	'''
}
stage('Archive') {
echo 'Archive the build'
archiveArtifacts artifacts: 'bazel-bin/main/hello-world', followSymlinks: true, onlyIfSuccessful: true
}

}
